#!/usr/bin/env bash

declare -a files=(
  ".alias"
  ".envvars"
  ".compton.conf"
  ".config/i3/config"
  ".config/rofi/config"
  ".config/polybar/config.ini"
  ".config/polybar/launch.sh"
  ".config/polybar/fonts/IosevkaNerdFont-Complete.ttf"
  ".config/polybar/fonts/Jua-Regular.ttf"
  ".tmux.conf"
  ".tmux.conf.local"
  ".vimrc"
  ".xinitrc"
  ".Xresources"
  ".zprofile"
  ".zshrc"
)
