#!/usr/bin/env bash

# create all subdirectories that don't exist
function create_subdirectories () {
  subdir=`echo ${1%*/*}`

  if [[ -d $HOME/.config/$subdir ]]; then
    mkdir -p $HOME/.config/$subdir
    echo -e "created $subdir\n"
  fi
}

source dotfiles
dir=`pwd`

for file in ${files[@]}; do

  # check if the file is nested
  if [[ $file == *"/"* ]]; then
    create_subdirectories $file
    ln -svf $dir/$file $HOME/$file
  else
    ln -svf $dir/$file $HOME/
  fi

done
